spring:
  application:
    name: "ecoton-backend"
  datasource:
    url: "jdbc:postgresql://ecoton-db:5432/ecoton-db"
    driver-class-name: "org.postgresql.Driver"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "create-drop"
    open-in-view: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${CLIENT_ID}"
            client-secret: "${CLIENT_SECRET}"

logging:
  level:
    org:
      springframework:
        security: debug

server:
  port: 8008